# Generated by Django 6.0 on 2025-12-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('comm', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'получатель рассылки',
                'verbose_name_plural': 'получатели рассылки',
            },
        ),
    ]
