# Generated by Django 6.0 on 2025-12-16 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='mailing.message', verbose_name='Сообщение')),
                ('receivers', models.ManyToManyField(to='mailing.receivermailing')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
