# Generated by Django 6.0 on 2025-12-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_message_owner_receivermailing_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_all_mailings', 'Может просматривать все рассылки'), ('can_disable_mailing', 'Может отключать рассылки (для менеджеров)'), ('can_manage_all_mailings', 'Может управлять всеми рассылками')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'ordering': ['-attempt_time'], 'permissions': [('can_view_all_attempts', 'Может просматривать все попытки рассылок')], 'verbose_name': 'попытка рассылки', 'verbose_name_plural': 'попытки рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('can_view_all_messages', 'Может просматривать все сообщения'), ('can_manage_messages', 'Может управлять сообщениями (для менеджеров)')], 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
        migrations.AlterModelOptions(
            name='receivermailing',
            options={'permissions': [('can_view_all_receivers', 'Может просматривать всех получателей'), ('can_manage_receivers', 'Может управлять получателями (для менеджеров)')], 'verbose_name': 'получатель рассылки', 'verbose_name_plural': 'получатели рассылки'},
        ),
    ]
