# Generated by Django 6.0 on 2025-12-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_avatar_customuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='messages_count',
            field=models.PositiveIntegerField(default=0, verbose_name='количество отправленных сообщений'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='successful_mailing_count',
            field=models.PositiveIntegerField(default=0, verbose_name='количество успешных рассылок'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unsuccessful_mailing_count',
            field=models.PositiveIntegerField(default=0, verbose_name='количество неуспешных рассылок'),
        ),
    ]
